//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="view_data", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApp_rsu")]
    [System.SerializableAttribute()]
    public partial class view_data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_pasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jns_kelaminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_pasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string no_telponField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tempat_lahirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tgl_lahirField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string agama {
            get {
                return this.agamaField;
            }
            set {
                if ((object.ReferenceEquals(this.agamaField, value) != true)) {
                    this.agamaField = value;
                    this.RaisePropertyChanged("agama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamat {
            get {
                return this.alamatField;
            }
            set {
                if ((object.ReferenceEquals(this.alamatField, value) != true)) {
                    this.alamatField = value;
                    this.RaisePropertyChanged("alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_pasien {
            get {
                return this.id_pasienField;
            }
            set {
                if ((object.ReferenceEquals(this.id_pasienField, value) != true)) {
                    this.id_pasienField = value;
                    this.RaisePropertyChanged("id_pasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jns_kelamin {
            get {
                return this.jns_kelaminField;
            }
            set {
                if ((object.ReferenceEquals(this.jns_kelaminField, value) != true)) {
                    this.jns_kelaminField = value;
                    this.RaisePropertyChanged("jns_kelamin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_pasien {
            get {
                return this.nama_pasienField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_pasienField, value) != true)) {
                    this.nama_pasienField = value;
                    this.RaisePropertyChanged("nama_pasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nik {
            get {
                return this.nikField;
            }
            set {
                if ((object.ReferenceEquals(this.nikField, value) != true)) {
                    this.nikField = value;
                    this.RaisePropertyChanged("nik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string no_telpon {
            get {
                return this.no_telponField;
            }
            set {
                if ((object.ReferenceEquals(this.no_telponField, value) != true)) {
                    this.no_telponField = value;
                    this.RaisePropertyChanged("no_telpon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tempat_lahir {
            get {
                return this.tempat_lahirField;
            }
            set {
                if ((object.ReferenceEquals(this.tempat_lahirField, value) != true)) {
                    this.tempat_lahirField = value;
                    this.RaisePropertyChanged("tempat_lahir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tgl_lahir {
            get {
                return this.tgl_lahirField;
            }
            set {
                if ((object.ReferenceEquals(this.tgl_lahirField, value) != true)) {
                    this.tgl_lahirField = value;
                    this.RaisePropertyChanged("tgl_lahir");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertdata_pasien", ReplyAction="http://tempuri.org/IService1/insertdata_pasienResponse")]
        string insertdata_pasien(string id_pasien, string nik, string nama_pasien, string tempat_lahir, string tgl_lahir, string agama, string jns_kelamin, string alamat, string no_telpon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertdata_pasien", ReplyAction="http://tempuri.org/IService1/insertdata_pasienResponse")]
        System.Threading.Tasks.Task<string> insertdata_pasienAsync(string id_pasien, string nik, string nama_pasien, string tempat_lahir, string tgl_lahir, string agama, string jns_kelamin, string alamat, string no_telpon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editdata_pasien", ReplyAction="http://tempuri.org/IService1/editdata_pasienResponse")]
        string editdata_pasien(string id_pasien, string nik, string nama_pasien, string tempat_lahir, string tgl_lahir, string agama, string jns_kelamin, string alamat, string no_telpon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editdata_pasien", ReplyAction="http://tempuri.org/IService1/editdata_pasienResponse")]
        System.Threading.Tasks.Task<string> editdata_pasienAsync(string id_pasien, string nik, string nama_pasien, string tempat_lahir, string tgl_lahir, string agama, string jns_kelamin, string alamat, string no_telpon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletedata_pasien", ReplyAction="http://tempuri.org/IService1/deletedata_pasienResponse")]
        string deletedata_pasien(string id_pasien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletedata_pasien", ReplyAction="http://tempuri.org/IService1/deletedata_pasienResponse")]
        System.Threading.Tasks.Task<string> deletedata_pasienAsync(string id_pasien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/caridata_pasien", ReplyAction="http://tempuri.org/IService1/caridata_pasienResponse")]
        WindowsFormsApp1.ServiceReference1.view_data[] caridata_pasien(string id_pasien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/caridata_pasien", ReplyAction="http://tempuri.org/IService1/caridata_pasienResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.view_data[]> caridata_pasienAsync(string id_pasien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listdata_pasien", ReplyAction="http://tempuri.org/IService1/listdata_pasienResponse")]
        WindowsFormsApp1.ServiceReference1.view_data[] listdata_pasien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listdata_pasien", ReplyAction="http://tempuri.org/IService1/listdata_pasienResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.view_data[]> listdata_pasienAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IService1>, WindowsFormsApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string insertdata_pasien(string id_pasien, string nik, string nama_pasien, string tempat_lahir, string tgl_lahir, string agama, string jns_kelamin, string alamat, string no_telpon) {
            return base.Channel.insertdata_pasien(id_pasien, nik, nama_pasien, tempat_lahir, tgl_lahir, agama, jns_kelamin, alamat, no_telpon);
        }
        
        public System.Threading.Tasks.Task<string> insertdata_pasienAsync(string id_pasien, string nik, string nama_pasien, string tempat_lahir, string tgl_lahir, string agama, string jns_kelamin, string alamat, string no_telpon) {
            return base.Channel.insertdata_pasienAsync(id_pasien, nik, nama_pasien, tempat_lahir, tgl_lahir, agama, jns_kelamin, alamat, no_telpon);
        }
        
        public string editdata_pasien(string id_pasien, string nik, string nama_pasien, string tempat_lahir, string tgl_lahir, string agama, string jns_kelamin, string alamat, string no_telpon) {
            return base.Channel.editdata_pasien(id_pasien, nik, nama_pasien, tempat_lahir, tgl_lahir, agama, jns_kelamin, alamat, no_telpon);
        }
        
        public System.Threading.Tasks.Task<string> editdata_pasienAsync(string id_pasien, string nik, string nama_pasien, string tempat_lahir, string tgl_lahir, string agama, string jns_kelamin, string alamat, string no_telpon) {
            return base.Channel.editdata_pasienAsync(id_pasien, nik, nama_pasien, tempat_lahir, tgl_lahir, agama, jns_kelamin, alamat, no_telpon);
        }
        
        public string deletedata_pasien(string id_pasien) {
            return base.Channel.deletedata_pasien(id_pasien);
        }
        
        public System.Threading.Tasks.Task<string> deletedata_pasienAsync(string id_pasien) {
            return base.Channel.deletedata_pasienAsync(id_pasien);
        }
        
        public WindowsFormsApp1.ServiceReference1.view_data[] caridata_pasien(string id_pasien) {
            return base.Channel.caridata_pasien(id_pasien);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.view_data[]> caridata_pasienAsync(string id_pasien) {
            return base.Channel.caridata_pasienAsync(id_pasien);
        }
        
        public WindowsFormsApp1.ServiceReference1.view_data[] listdata_pasien() {
            return base.Channel.listdata_pasien();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.view_data[]> listdata_pasienAsync() {
            return base.Channel.listdata_pasienAsync();
        }
    }
}
